/*
 * HOME_PAGE_PLACEHOLDER
 * BRANDED_PRODUCT_NAME_PLACEHOLDER LIBRARY_PLACEHOLDER Client
 * Version VERSION_PLACEHOLDER build BUILD_PLACEHOLDER
 * Copyright (c) Lightstreamer Srl. All Rights Reserved.
 * Contains: CLASSES_PLACEHOLDER
 * TYPE_PLACEHOLDER
 */
